#生产环境
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ucan_admin?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 1500
      min-idle: 1
      max-wait: 60000